### ISSUE TITLE
Support for minSDKVersion=19

### ISSUE THREAD

**Issue by reustonium** [shem8/MaterialLogin#1]
Is it worthwhile to consider adding support for pre-lollipop devices?  Targeting API-19 get's you 36.1% more device coverage.

**Comment by reustonium** [comment]
I forked your repo and changed minSDKVersion = 19 in both the library and app, and it compiles and runs fine.

Applying this update would make your library usable to developer's targeting pre-lollipop devices.  I'll submit a PR for you to consider.

Thanks!

**Comment by shem8** [comment]
Thanks for you help!

I've been answering you in the PR, the ViewAnimationUtils was added only in API 21.
Changing the min sdk is indeed something wort doing, maybe using [CircularReveal] (https://github.com/ozodrukh/CircularReveal)?

**Comment by shem8** [comment]
Fixed: https://github.com/shem8/MaterialLogin/pull/10
