### ISSUE TITLE
FAB Animation is broken on API-16

### ISSUE THREAD

**Issue by reustonium** [shem8/MaterialLogin#12]
![image](https://cloud.githubusercontent.com/assets/1432186/12677195/365e2dee-c665-11e5-89a2-3f7ec1f38f51.gif)

**Comment by shem8** [comment]
OK, that took me some time and actually there is a really hard bug to spot in the Android platform, but I managed to fix him, more about it here: [http://stackoverflow.com/questions/35046210/floating-action-button-animation-issue/37069521#37069521](url)

Thanks for pointing it out!
