### ISSUE TITLE
separate listener for login and register buttons

### ISSUE THREAD

**Issue by focusvce** [shem8/MaterialLogin#15]
Provide with a suitable on click listener for login and register buttons instead of view listener as a whole. That will provide us with more control over functioning of the application. Because the basic task for the login form is to communicate with the server that requires lot of back end processing when the user has to validated from the server scripts. Fix it asap.

**Comment by shem8** [comment]
Indeed going to change it just to add click listener, but till the next version- why can't you do heavy lifting with login on server with the current design with one listener?

**Comment by focusvce** [comment]
The template which you have made is great but when we are trying to verify that a user is valid on not (Sign In) , it's actually very hard , because the moment we need the response is after clicking the button, but the view is listening all the time hence we get empty response from the server. We (foucsvce community ) are beginners and really need this template.
Please fix it as soon as possible and provide it with separate button on click listeners. 
Thanks, eagarly waiting for next version.

**Comment by shem8** [comment]
It might take me couple of days to upload this fix but I really think we might work together to make it work with the current design, cause the current way it works is that I add the click listener to the button.

Can you tell a me a bit more about the problem you have? because I don't fully understand the problem.

**Comment by shem8** [comment]
Added on v2.1.0
