### ISSUE TITLE
hide register option

### ISSUE THREAD

**Issue by paxdron** [shem8/MaterialLogin#16]
What if I only require a login and not a register option
Is there any way to hide the "+" ?

**Comment by shem8** [comment]
Currently no, I'm not sure it's something that many will want. Do you need this kind of functionality?

**Comment by lauborges** [comment]
I need it too

**Comment by rohansood42** [comment]
totally need it.

**Comment by shem8** [comment]
OK, good to know. Will add it...

**Comment by shem8** [comment]
Added: https://github.com/shem8/MaterialLogin/commit/b19fafcdf289ff5d84db080bd408393dfab480e9

You can now use `registerTitle` attribute in the login view
