### ISSUE TITLE
Force Closes after a wrong password attempt

### ISSUE THREAD

**Issue by fayazara** [shem8/MaterialLogin#22]
Whenever I enter a wrong password and enter the correct password again, app force closes. Weird right!

**Comment by shem8** [comment]
The library doesn't do a password verification, are you sure it's not on your implementation?

**Comment by tangchao0106** [comment]
Error:Plugin with id 'com.github.dcendents.android-maven' not found.

**Comment by shem8** [comment]
I'm not using the android-maven plugin =|
Can you elaborate?
