### ISSUE TITLE
where is "io.codetail.animation.SupportAnimator"

### ISSUE THREAD

**Issue by JiangShuLiang** [shem8/MaterialLogin#23]
The login effect that you make is very brilliant. I like it very much!
but here is a problem for me:
I imported this lib into my workspace by eclipse.
but I can't find "io.codetail.animation.SupportAnimator" and "io.codetail.animation.ViewAnimationUtils".
could you tell me where this lib is?
much thanks in advance.

**Comment by shem8** [comment]
I'm using a 3rd party library to support animation on old api's, you can find it here: https://github.com/ozodrukh/CircularReveal

**Comment by JiangShuLiang** [comment]
thanks!
I had import the 3rd party library according to the address that you provide.but I still can't find "io.codetail.animation.SupportAnimator" in the 3rd party library.
pls check the picture attached.
thanks again.

**Comment by JiangShuLiang** [comment]
I can find ViewAnimationUtils in this 3rd party library
but for SupportAnimator, it does not exist in this 3rd party library for sure.

**Comment by shem8** [comment]
Try changing

```groovy
compile ('com.github.ozodrukh:CircularReveal:1.3.1@aar') {
        transitive = true;
}
```

to

```groovy
compile ('com.github.ozodrukh:CircularReveal:1.1.1@aar') {
        transitive = true;
}
```

(source: https://github.com/ozodrukh/CircularReveal/issues/67)
Let me know if that was the problem and I'll change it in the Readme file.

**Comment by JiangShuLiang** [comment]
thanks very much,it works.
but the method setStartDelay(200) still can't be find.so I have to comment it out.

**Comment by shem8** [comment]
It should be ok now in the v2.2.0
