### ISSUE TITLE
Library is not optimized for RTL layouts

### ISSUE THREAD

**Issue by Sdghasemi** [shem8/MaterialLogin#25]
First of all thanks for the great library. The problem is when I try using **RTL layouts**, registration fab locates on the **upper-left corner** of dialog as expected but after clicking it animates to its **bottom-left direction** which is the behavior for the LTR layouts, instead of bottom-right. It also happens for the reveal effect which incorrectly starts from the right half of dialog. And also the "Register" dialog title has left gravity.
What can I do?

**Comment by shem8** [comment]
First of all- thanks!

Second- you're right, I didn't tested the lib on RTL =\
You can open a pull request, this probably is a small fix, or you can wait for me to fix it...

**Comment by shem8** [comment]
Fixed in v2.1.0

**Comment by Sdghasemi** [comment]
Thanks for the update, but the open reveal effect is still staring from the right half in RTL mode (should be left).
I think the fix would be this:
`SupportAnimator animator = getCircularRevealAnimation(registerCard, mIsRTL ? 250 : registerView.getWidth() - 250, 400, 0f, 2F * registerView.getHeight());`

**Comment by shem8** [comment]
Yup, you're right,
Can you please open a pull request for this?

**Comment by Sdghasemi** [comment]
@shem8 pull requested: #30 :)

**Comment by shem8** [comment]
approved and merged to developed, Thanks!
Do you need me to publish a new version to Maven or you're using it locally?

**Comment by Sdghasemi** [comment]
I'm using it through my own published repository in Maven for now. but if you publish a new version to Maven, I'll be happy to replace it with yours.

**Comment by StefMa** [comment]
Can be closed i guess

**Comment by shem8** [comment]
Keeping it open for remeber to merge it to master and deploy to maven.
