### ISSUE TITLE
Cannot getText! NullPointerException

### ISSUE THREAD

**Issue by nuhkoca** [shem8/MaterialLogin#40]
Hi Dear Developer,

Whenever I want to test that I enter an incorrect username or password app always crashes. getText is not working for me for the time being. Can you please help me solve?

Attached are screenshots demonstrate this situation. Soonest reply is highly appreciated.

![screen shot 2017-05-06 at 15 51 07](https://cloud.githubusercontent.com/assets/5719389/25772447/87fc0948-3273-11e7-98fd-8ef0f01d3c61.png)
![screen shot 2017-05-06 at 15 51 15](https://cloud.githubusercontent.com/assets/5719389/25772448/880102cc-3273-11e7-847b-4217e01e4518.png)

**Comment by shem8** [comment]
This is really weird, looks like you're doing it like you suppose to. Are you able to reproduce it constantly?
Can you share the full class?

**Comment by nuhkoca** [comment]
Dear shem8,

Please find the full class below: I hope you will fix my issue :) Tnx in advance!

package com.endroidteam.actimo.activities;

import android.database.Cursor;
import android.os.Bundle;
import android.support.design.widget.Snackbar;
import android.support.design.widget.TextInputLayout;
import android.support.v7.app.AppCompatActivity;

import com.endroidteam.actimo.R;

import shem.com.materiallogin.DefaultLoginView;
import shem.com.materiallogin.DefaultRegisterView;
import shem.com.materiallogin.MaterialLoginView;

public class LoginActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);

        final MaterialLoginView login = (MaterialLoginView) findViewById(R.id.login);
        ((DefaultLoginView) login.getLoginView()).setListener(new DefaultLoginView.DefaultLoginViewListener() {

            @Override
            public void onLogin(TextInputLayout loginUser, TextInputLayout loginPass) {
                String user = loginUser.getEditText().getText().toString();
                if (user.isEmpty()) {
                    loginUser.setError("User name can't be empty");
                    return;
                }
                loginUser.setError("");

                String pass = loginPass.getEditText().getText().toString();
                if (!pass.equals(user)) {
                    loginPass.setError("Wrong password");
                    return;
                }
                loginPass.setError("");

                Snackbar.make(login, "Login success!", Snackbar.LENGTH_LONG).show();
            }
        });

        ((DefaultRegisterView) login.getRegisterView()).setListener(new DefaultRegisterView.DefaultRegisterViewListener() {
            @Override
            public void onRegister(TextInputLayout registerUser, TextInputLayout registerPass, TextInputLayout registerPassRep) {
                String user = registerUser.getEditText().getText().toString();
                if (user.isEmpty()) {
                    registerUser.setError("User name can't be empty");
                    return;
                }
                registerUser.setError("");

                String pass = registerPass.getEditText().getText().toString();
                if (pass.isEmpty()) {
                    registerPass.setError("Password can't be empty");
                    return;
                }
                registerPass.setError("");

                String passRep = registerPassRep.getEditText().getText().toString();
                if (!pass.equals(passRep)) {
                    registerPassRep.setError("Passwords are different");
                    return;
                }
                registerPassRep.setError("");

                Snackbar.make(login, "Register success!", Snackbar.LENGTH_LONG).show();
            }
        });
    }

**Comment by shem8** [comment]
Again, the code looks good, are you able to run the example app?

**Comment by nuhkoca** [comment]
Hi, Yes I am able to run the app but it crashes while I am entering unlike credentials(username, password), now register button is not working, either :/
