### ISSUE TITLE
Name convention

### ISSUE THREAD

**Issue by StefMa** [shem8/MaterialLogin#7]
Actually we have two different names.
`MaterialLogin` and `LoginView`. 
* This repo is called `MaterialLogin` 
* The [view](https://github.com/shem8/MaterialLogin/blob/master/material-login/src/main/java/shem/com/materiallogin/LoginView.java) is called `LoginView`
* The [Theme](https://github.com/shem8/MaterialLogin/blob/master/material-login/src/main/res/values/styles.xml) called `MaterialLoginTheme`
* The [attributes](https://github.com/shem8/MaterialLogin/blob/master/material-login/src/main/res/values/attrs.xml) called `MaterialLoginView`
* The [colors](https://github.com/shem8/MaterialLogin/blob/master/material-login/src/main/res/values/colors.xml) called `MaterialLogin*Color`

only for a few.

I think it would be great if we have on Name for all. `MaterialLogin` OR `LoginView` then the ressources above look like
* This repo is called `MaterialLogin` 
* The [view](https://github.com/shem8/MaterialLogin/blob/master/material-login/src/main/java/shem/com/materiallogin/LoginView.java) is called `MaterialLoginView`
* The [Theme](https://github.com/shem8/MaterialLogin/blob/master/material-login/src/main/res/values/styles.xml) called `MaterialLoginTheme`
* The [attributes](https://github.com/shem8/MaterialLogin/blob/master/material-login/src/main/res/values/attrs.xml) called `MaterialLogin`
* The [colors](https://github.com/shem8/MaterialLogin/blob/master/material-login/src/main/res/values/colors.xml) called `MaterialLogin*Color`

OR
* This repo is called `LoginView` 
* The [view](https://github.com/shem8/MaterialLogin/blob/master/material-login/src/main/java/shem/com/materiallogin/LoginView.java) is called `LoginView`
* The [Theme](https://github.com/shem8/MaterialLogin/blob/master/material-login/src/main/res/values/styles.xml) called `LoginViewTheme`
* The [attributes](https://github.com/shem8/MaterialLogin/blob/master/material-login/src/main/res/values/attrs.xml) called `LoginView`
* The [colors](https://github.com/shem8/MaterialLogin/blob/master/material-login/src/main/res/values/colors.xml) called `LoginView*Color`

I preffer the first one because :+1:

**Comment by shem8** [comment]
Agree, lets go with the first one.

**Comment by shem8** [comment]
Fixed:
https://github.com/shem8/MaterialLogin/commit/3c2007ec875eaa00b3bb0d5f385550409d2e0871
